shortly:
  url-service:
    base-url: ${URL_SERVICE_BASE_URL:http://localhost:8081}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
