services:
  mysql-url:
    image: mysql:8.0
    container_name: shortly-mysql-url
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shortly_url
    ports:
      - "3307:3306"
    volumes:
      - mysql-url-data:/var/lib/mysql
    networks:
      - shortly-network

  mysql-click:
    image: mysql:8.0
    container_name: shortly-mysql-click
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shortly_click
    ports:
      - "3309:3306"
    volumes:
      - mysql-click-data:/var/lib/mysql
    networks:
      - shortly-network

  redis:
    image: redis:7-alpine
    container_name: shortly-redis
    ports:
      - "6379:6379"
    networks:
      - shortly-network

  kafka:
    image: apache/kafka:3.7.0
    container_name: shortly-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - shortly-network

networks:
  shortly-network:
    name: shortly-network

volumes:
  mysql-url-data:
  mysql-click-data:
