services:
  prometheus:
    image: prom/prometheus:latest
    container_name: shortly-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: shortly-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ../monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ../monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    networks:
      - monitoring-network

networks:
  monitoring-network:
    name: monitoring-network
