services:
  # URL Service Database
  mysql-url:
    image: mysql:8.0
    container_name: shortly-mysql-url
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shortly_url
    ports:
      - "3306:3306"
    volumes:
      - mysql-url-data:/var/lib/mysql
    networks:
      - shortly-network
    command: --default-authentication-plugin=mysql_native_password

  # Click Service Database
  mysql-click:
    image: mysql:8.0
    container_name: shortly-mysql-click
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shortly_click
    ports:
      - "3307:3306"
    volumes:
      - mysql-click-data:/var/lib/mysql
    networks:
      - shortly-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: shortly-redis
    ports:
      - "6379:6379"
    volumes:
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - shortly-network

  kafka:
    image: apache/kafka:3.7.0
    container_name: shortly-kafka
    cap_add:
      - NET_ADMIN
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,EXTERNAL://${KAFKA_EXTERNAL_HOST:-localhost}:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_HEAP_OPTS: "-Xmx1g -Xms1g"
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 1024M
    networks:
      - shortly-network

networks:
  shortly-network:
    name: shortly-network

volumes:
  mysql-url-data:
  mysql-click-data:
  redis-data:
