spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shortly?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 50         # Phase 1, 2와 동일
      minimum-idle: 10
      connection-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: create-drop        # 테스트용
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      time-to-live: 600000          # 10분

server:
  port: 8080
  tomcat:
    threads:
      max: 500                      # Phase 1, 2와 동일

logging:
  level:
    com.io.shortly: INFO
